baseURL: "https://aliiiw.github.io/"
languageCode: "en-us"
title: "Ali's Tech Notes"
theme: "PaperMod"

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  TocOpen: false

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
