baseURL = "https://blog.alirahimi.dev/"
languageCode = "en-us"
title = "Ali Rahimi"
theme = "PaperMod"

timeZone = "Europe/Paris"

[pagination]
pagerSize = 10

# --- Ordering: newest first (by date/publishDate/lastmod)
[frontmatter]
date = ["publishDate", "date", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

# مثل همون سایت: categories + tags
[taxonomies]
tag = "tags"
category = "categories"

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowLastMod = true
mainSections = ["posts"]

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"


# همون حالت صفحه‌ی اول: "Hi there" + یک متن کوتاه
[params.homeInfoParams]
Title = "Hi there this is the blog for me sharing my ideas with others in Android Field"
Content = "Under Construction…"

# آیکن‌های شبکه‌های اجتماعی
[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/alii-rahimi/"

[[params.socialIcons]]
name = "email"
url = "mailto:aliirahimioriginal@gmail.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Aliiiw"

# منوی بالا
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "categories"
url = "/categories/"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags/"
weight = 3
